### PR TITLE
Use the `maintainers` directive in spackbot

### PR DESCRIPTION
**Pull request by adamjstewart**

### CODE REVIEW

**Review by scottwittenburg — APPROVED** [review]

**Comment by adamjstewart** [comment]
Also need to update `parse_maintainers_from_patch` to be able to detect maintainers from `package.py` without running Spack.

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
@scottwittenburg feel free to merge this

**Comment by adamjstewart** [comment]
What's the process for deploying this?

**Comment by scottwittenburg** [comment]
> What's the process for deploying this?

It is deployed from [here](https://github.com/spack/spack-infrastructure/blob/main/k8s/spack/spackbot-spack-io/deployments.yaml), and it requires kube access, but is straightforward even if currently manual.  I'll deploy it today.

**Comment by scottwittenburg** [comment]
The new version including #73 and #74 is deployed.

**Pull request merged**
